import {ScrollArea} from "@/components/ui/scroll-area";
import {Separator} from "@radix-ui/react-menu";

export default function TermsOfService() {
    return (
        <div className="min-h-screen flex flex-col pt-8">
            <header className="py-4">
                <div className="container mx-auto px-8">
                    <h1 className="text-2xl font-semibold">
                        <span className="text-primary">te</span>/rms of service
                    </h1>
                </div>
            </header>

            <main className="flex-grow container mx-auto px-8 py-8">
                <div className="flex flex-col md:flex-row gap-8">
                    <aside className="md:w-1/4">
                        <TableOfContents />
                    </aside>
                    <div className="md:w-3/4">
                        <ScrollArea className="h-[calc(100vh-12rem)]">
                            <TermsContent />
                        </ScrollArea>
                    </div>
                </div>
            </main>
        </div>
    )
}

function TableOfContents() {
    const sections = [
        "Introduction",
        "Acceptance of Terms",
        "Description of Service",
        "User Accounts",
        "User Content",
        "Intellectual Property Rights",
        "Privacy Policy",
        "Limitation of Liability",
        "Modifications to Service",
        "Termination",
        "Governing Law",
        "Contact Information"
    ]

    return (
        <nav className="sticky top-4">
            <h2 className="text-lg font-semibold mb-4">Table of Contents</h2>
            <ul className="space-y-2">
                {sections.map((section, index) => (
                    <li key={index}>
                        <a href={`#${section.toLowerCase().replace(/\s+/g, '-')}`} className="text-sm hover:underline">
                            {section}
                        </a>
                    </li>
                ))}
            </ul>
        </nav>
    )
}

function TermsContent() {
    return (
        <div className="space-y-8">
            <Section id="introduction" title="Introduction">
                <p>
                    Welcome to ai/tinera. These Terms of Service govern your use of our website and services.
                    By using our app, you agree to these terms. Please read them carefully.
                </p>
            </Section>

            <Section id="acceptance-of-terms" title="Acceptance of Terms">
                <p>
                    By accessing or using the ai/tinera, you acknowledge that you have read,
                    understood, and agree to be bound by these Terms of Service. If you do not agree to these terms,
                    please do not use our service.
                </p>
            </Section>

            <Section id="description-of-service" title="Description of Service">
                <p>
                    ai/tinera provides an artificial intelligence-powered service that creates personalized
                    travel itineraries based on user inputs and preferences. The service uses machine learning algorithms
                    to generate suggestions and plan details.
                </p>
            </Section>

            <Section id="user-accounts" title="User Accounts">
                <p>
                    To use certain features of the service, you may be required to create an account. You are responsible
                    for maintaining the confidentiality of your account information and for all activities that occur under
                    your account.
                </p>
            </Section>

            <Section id="user-content" title="User Content">
                <p>
                    By submitting information, preferences, or any other content to our service, you grant ai/tinera
                    a worldwide, non-exclusive, royalty-free license to use, reproduce, and display such content for the
                    purpose of providing and improving our service.
                </p>
            </Section>

            <Section id="intellectual-property-rights" title="Intellectual Property Rights">
                <p>
                    The ai/tinera service, including its software, algorithms, and content generated by the AI,
                    is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used
                    in connection with any product or service without our prior written consent.
                </p>
            </Section>

            <Section id="privacy-policy" title="Privacy Policy">
                <p>
                    Your use of ai/tinera is also governed by our Privacy Policy, which is incorporated into
                    these Terms of Service by reference. Please review our Privacy Policy to understand how we collect,
                    use, and disclose information about you.
                </p>
            </Section>

            <Section id="limitation-of-liability" title="Limitation of Liability">
                <p>
                    ai/tinera and its affiliates, officers, employees, agents, partners, and licensors shall not
                    be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting
                    from your use or inability to use the service.
                </p>
            </Section>

            <Section id="modifications-to-service" title="Modifications to Service">
                <p>
                    We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof)
                    with or without notice. You agree that ai/tinera shall not be liable to you or to any third party
                    for any modification, suspension, or discontinuance of the service.
                </p>
            </Section>

            <Section id="termination" title="Termination">
                <p>
                    We may terminate or suspend your account and access to the service immediately, without prior notice or
                    liability, for any reason whatsoever, including without limitation if you breach these Terms of Service.
                </p>
            </Section>

            <Section id="governing-law" title="Governing Law">
                <p>
                    These Terms of Service shall be governed by and construed in accordance with the laws of Nevada,
                    without regard to its conflict of law provisions.
                </p>
            </Section>

            <Section id="contact-information" title="Contact Information">
                <p>
                    If you have any questions about these Terms of Service, please contact us at:
                </p>
                <p className="mt-2">
                    <a href="mailto:support@aitiniera.com" className="hover:underline">
                        support@aitiniera.com
                    </a>
                </p>
            </Section>
        </div>
    )
}

function Section({ id, title, children }: { id: string, title: string, children: React.ReactNode }) {
    return (
        <section id={id} className="scroll-mt-16">
            <h2 className="text-xl font-semibold mb-4">{title}</h2>
            {children}
            <Separator className="mt-8" />
        </section>
    )
}
